class PartyPageData {
  static final view="VIEWS";
  static final followers="FOLLOWERS";
  static final following="FOLLOWING";
  static final info="INFO";
  static final symbol="SYMBOL";
  static final journey="JOURNEY";
  static final leadership="LEADERSHIP";
  static final feed="FEED";
  static final event="EVENT";
  static final manifesto="MANIFESTO";
  static final founded="FOUNDED";
  static final favoriteIcon="Assets/PartyPage/favourite.svg";
  static final flagIcon="Assets/PartyPage/flagIcon.svg";
  static final foundedIcon="Assets/PartyPage/foundedIcon.svg";
  static final globalIcon="Assets/PartyPage/globalIcon.svg";
  static final headquarterIcon="Assets/PartyPage/headquarterIcon.svg";
  static final personIcon="Assets/PartyPage/personIcon.svg";
}